name: Build Docker Image on Push

on:
  push:
    paths:
      - '**'  # Watches all files in the repository

jobs:
  build-docker-image:
    runs-on: self-hosted  # Ensure it runs on your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          # Navigate to the backend folder and build the Docker image
          cd backend
          docker build -t cicd_backend .
