name: Notify on Push

on:
  push:
    paths:
      - '**'  # Watches all files in the repository

jobs:
  send-message:
    runs-on: self-hosted  # Ensure it runs on your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send message
        run: echo "wow"
